# -*- coding: utf-8 -*-
"""演習問題2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3yd3C2v6bCmf3ydL4NjOKgXLBAMv3xO
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# 1. ファイルを読み込んで変数df2 に代入しなさい
df6 = pd.read_csv("http://160.247.113.166/foot1k_na.csv")

# 2. 各列の欠損値の数を調べなさい
print(df6.isna().sum())

# 3. df6 を df7 にコピーしなさい（以降の処理は df7 で行う)
df7 = df6.copy()

# 4. 欠損値がある列について，それぞれの中央値を求めて適当な変数に保存しなさい
median_height = df7['height'].median()
median_weight = df7['weight'].median()
median_footsize = df7['footsize'].median()

# 5. 欠損値を上で計算した中央値で埋めなさい．
df7['height'].fillna(median_height, inplace=True)
df7['weight'].fillna(median_weight, inplace=True)
df7['footsize'].fillna(median_footsize, inplace=True)

# 6. 各列の欠損値の数が 0 になったことを確認しなさい
print(df7.isna().sum())