# -*- coding: utf-8 -*-
"""演習問題1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTxmP5hjcybrxV6yJQGpK_qwB7I4rD4l
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# 1. ファイルを読み込んで変数df2 に代入しなさい
df2 = pd.read_csv("http://160.247.113.166/foot1k.csv")

# 2. height, weight, footsize を説明変数 X2, country をクラス y2 としなさい
X2 = df2[['height', 'weight', 'footsize']]
y2 = df2['country']

# 3. 全体の25%をテストデータとして，訓練データとテストデータに分割しなさい
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2, y2)

# 4. 訓練データでロジスティック回帰モデル lr2 を学習しなさい
lr2 = LogisticRegression()
lr2.fit(X2_train, y2_train)

# 5. テストデータを入力として予測を行いなさい
y2_pred = lr2.predict(X2_test)
print(y2_pred)