# -*- coding: utf-8 -*-
"""演習問題 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EcUE58z8B_nIs7LrZVIk2RwA7mB76tfV
"""

import pandas as pd
from sklearn.model_selection import train_test_split

# 1. http://bit.ly/41843Av を読み込んで変数 df に代入しなさい (※ 先ほどと同じファイルなので再実行は不要)．
df = pd.read_csv('http://bit.ly/41843Av', header=None)

# 2. df の最初の 5 行を出力しなさい．
print(df.head(5))

# 3. df の最初の2列を変数 X (←事例) に代入しなさい．
x = df.iloc[:, 0:2]

# 4. df の 3 列目を変数 y (←ラベル) に代入しなさい．
y = df.iloc[:, 2]

# 5. X と y を 8:2 の割合で訓練データとテストデータに分割しなさい．
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

# 6. 分割されたデータのサイズを確認しなさい
print("\nShapes of split data:")
print("x_train:", x_train.shape)
print("x_test :", x_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)