# -*- coding: utf-8 -*-
"""演習問題2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0I5K0vWDUMoRwZP0pWovSBiQzpuV6r0
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. ファイル http://bit.ly/41843Av を読み込んで変数 df に代入しなさい (※ 拡張子は無いがCSVファイル)
df = pd.read_csv('http://bit.ly/41843Av', header=0)

# 2. 先頭の 3 行を表示しなさい
print(df.head(3))

# 3. 列ごとの基本統計量を計算・表示しなさい
print(df.describe())

# 4. df の最初の列のヒストグラムを描きなさい
df['Height'].plot.hist()

# 5. df の最初の2列を使って散布図を描きなさい．x，y はどちらの列でも良い
df.plot.scatter(x='Height', y='Weight')