# -*- coding: utf-8 -*-
"""演習問題1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iA5T0Hq9MfSl9KwLBzpvxgBNIMoXLnmd
"""

import numpy as np

# 1. サイズ 3×5 の整数の配列 a とサイズ 2×5 の整数の配列 bを0〜99の乱数で作りなさい
a = np.random.randint(0, 100, (3, 5))
b = np.random.randint(0, 100, (2, 5))

# 2. a の (1から数えて) 2〜3行目を取り出して配列 c を作りなさい
c = a[1:3, :]

# 3. b + c を計算しなさい
bc = b + c

# 4. c をサイズ 5×2 に変形した配列 d を作りなさい
d = c.reshape(5, 2)

# 5. a と d のサイズを (確認のため) 表示してから，a と d の行列積を計算しなさい
print("a:", a.shape)
print("d:", d.shape)

ad = np.matmul(a, d)
print("a × d =\n", ad)