# -*- coding: utf-8 -*-
"""演習問題1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pUCq5v_6h0Mes9aTAgnMVE0pbIbYwWzO
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
model2 = LinearRegression()

#1. ファイル読み込んで変数df に代入しなさい
df = pd.read_csv('http://160.247.113.166/foot1k.csv')

#2. 先頭の 3 行を表示しなさい．
print(df.head(3))

#3. weight を説明変数 X2, footsize を目的変数 y2 としなさい
X2 = df[['weight']]
y2 = df['footsize']

# 4. 7:3 の割合で訓練データとテストデータに分割しなさい．(X2_, y2_ で始まる変数名を使うこと)
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2, y2, test_size=0.3
)

# 5. 訓練データで線形回帰モデル model2 を学習しなさい
model2.fit(X2_train, y2_train)

# 6. 学習したパラメタを表示しなさい
print("切片(intercept):", model2.intercept_)
print("回帰係数(coef):", model2.coef_)

# 7. テストデータを入力として予測を行いなさい
y2_pred = model2.predict(X2_test)
print("予測結果:")
print(y2_pred)