# -*- coding: utf-8 -*-
"""演習問題2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hktvtQdSnkgXXXLjbXBXNNRJJqWbZRZe
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
model2 = LinearRegression()

# 1. 読み込んで変数 dfに代入しなさい
df = pd.read_csv('http://160.247.113.166/foot1k.csv')

# 2. weight, height を説明変数 X2, footsize を目的変数 y2 としなさい
X2 = df[['weight', 'height']]
y2 = df['footsize']

# 3. 7:3 の割合で訓練データとテストデータに分割しなさい
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2, y2, test_size=0.3
)

# 4. 訓練データで線形回帰モデル model2 を学習しなさい
model2.fit(X2_train, y2_train)

# 5. 学習したパラメタを表示しなさい
print("切片 (intercept):", model2.intercept_)
print("回帰係数 (coef):", model2.coef_)

# 6. 訓練データ，テストデータそれぞれで決定係数を計算しなさい
print("訓練データ:", model2.score(X2_train, y2_train))
print("テストデータ:", model2.score(X2_test, y2_test))