# -*- coding: utf-8 -*-
"""演習問題4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bWeBGLg66waxpEa5qiDP6XTxJLvvlvpq
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
model3 = LinearRegression()
scaler = StandardScaler()

df = pd.read_csv('http://160.247.113.166/foot1k.csv')

# 1. height, weight, country_US を説明変数とし，いずれも標準化しなさい
df_dum = pd.get_dummies(df, columns=['country'], drop_first=True)
X3 = df_dum[['height', 'weight', 'country_US']]
y3 = df_dum['footsize']

X3_std = scaler.fit_transform(X3)
X3_train, X3_test, y3_train, y3_test = train_test_split(
    X3_std, y3, test_size=0.3
)

# 2. footsize を目的変数として，線形回帰モデル model3 を学習しなさい．
model3.fit(X3_train, y3_train)

# 3. 学習したパラメタ（傾き）を表示しなさい．
print("切片 (intercept):", model3.intercept_)
print("回帰係数 (coef):", model3.coef_)

#4. テストデータで決定係数と MSE を算出しなさい
r2_test = model3.score(X3_test, y3_test)
y3_pred = model3.predict(X3_test)
mse_test = mean_squared_error(y3_test, y3_pred)
print("テストデータ 決定係数:", r2_test)
print("テストデータ MSE:", mse_test)