# -*- coding: utf-8 -*-
"""演習問題3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1noa5Gv1TZ5nuw0IvlbVHRUHpi7KL_sD1
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
model2 = LinearRegression()
scaler = StandardScaler()

# 1. 読み込んで変数 df に代入しなさい
df = pd.read_csv('http://160.247.113.166/foot1k.csv')

# 2. weight, height を説明変数 X2, footsize を目的変数 y2 としなさい
X2 = df[['weight', 'height']]
y2 = df['footsize']

# 3. 説明変数 X2 を標準化しなさい
X2_std = scaler.fit_transform(X2)

# 4. 7:3 の割合で訓練データとテストデータに分割しなさい．
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2_std, y2, test_size=0.3
)

# 5. 訓練データで線形回帰モデル model2 を学習しなさい
model2.fit(X2_train, y2_train)

# 6. 学習したパラメタを表示しなさい
print("切片 (intercept):", model2.intercept_)
print("回帰係数 (coef):", model2.coef_)