# -*- coding: utf-8 -*-
"""November06_22-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G4QetTxI7BPecq6d-WULHVPYrVxMYqDP
"""

f1 = open('/content/drive/MyDrive/ColabNotebooks/test1.txt','r', encoding='UTF-8')
f2 = open('/content/drive/MyDrive/ColabNotebooks/test2.txt', 'w', encoding='UTF-8')

text = f1.read()
text_replaced = text.replace("AI", "人工知能")

f2.write("72570001 SEOYEONGWOO\n")
f2.write(text_replaced)

print("test2.txt に書き込みが完了しました。")

f1.close()
f2.close()