# -*- coding: utf-8 -*-
"""November06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19HlmBZrwJusAXMvN4GT6WCoPLdT9_xc3
"""

!pip install spacy
!pip install ginza ja-ginza
import spacy
nlp = spacy.load('ja_ginza')
doc = nlp('今年はドジャースが優勝して大谷が大活躍，いい年だなあ．')
for sent in doc.sents:
  for token in sent:
    print(token.i, token.orth_, token.lemma_, token.pos_,
      token.tag_)

'甲南'+'太郎'

'甲南'*3

len('甲南')

name ='甲南大学,神戸大学,神戸学院大学,甲南女子大学'
name.count('大学')

'python'[1]

'python'[2:5]

't' in 'python'

'k' in 'python'

# coding: utf-8
'甲南太郎が甲南花子と一緒に甲南大学と甲南女子大学の学園祭に行った'.split('甲南')

# coding: utf-8
'甲南'.join(['私は', '太郎が', '花子と一緒に', '大学と', '女子大学の学園祭に行った'])

t1 = '今日はいい天気です'
print(t1.replace('今日', '明日'))